import {
  Controller,
  Put,
  Query,
  Req,
  BadRequestException,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import type { Request } from 'express';
import { StorageService } from './storage.service';

@ApiTags('Storage')
@Controller('storage')
export class StorageController {
  constructor(private readonly storageService: StorageService) {}

  /**
   * Accepts raw file bytes at a signed URL generated by StorageService.getPresignedUploadUrl().
   * No auth header needed — the signed query params are the authorization.
   */
  @Put('upload')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Upload file via signed URL (used by mobile)' })
  async handleUpload(
    @Query('key') key: string,
    @Query('expires') expires: string,
    @Query('sig') sig: string,
    @Req() req: Request,
  ) {
    if (!key || !expires || !sig) {
      throw new BadRequestException('Missing upload token parameters');
    }

    if (!this.storageService.verifyUploadToken(key, parseInt(expires, 10), sig)) {
      throw new BadRequestException('Invalid or expired upload token');
    }

    // req.body is a Buffer because we apply express.raw() for this route in main.ts
    const buffer: Buffer = req.body;
    if (!buffer || buffer.length === 0) {
      throw new BadRequestException('Empty file');
    }

    this.storageService.saveFile(key, buffer);
    return { message: 'Uploaded successfully' };
  }
}
